### ISSUE TITLE
TS2786: Mjml cannot be used as a JSX component.

### ISSUE THREAD

**Issue by kirill-konshin** [Faire/mjml-react#111]
"mjml-react": "^2.0.8",
"@types/mjml-react": "^2.0.10",

![image](https://github.com/Faire/mjml-react/assets/1530410/1da9780a-3f38-42f8-b718-42c2651700b3)

![image](https://github.com/Faire/mjml-react/assets/1530410/d16410fb-a4dd-4169-bdf3-c10a52fe6d89)

**Comment by emmclaughlin** [comment]
Hi @kirill-konshin 👋 

`mjml-react` and `@types/mjml-react` are not a part of this project. They are from https://github.com/wix-incubator/mjml-react, which is no longer maintained. We forked that project and took over maintaining it under `@faire/mjml-react`.

I would recommend upgrading to the latest version of `@faire/mjml-react` and seeing if the error still persists. Our components are written in typescript (example: [Mjml](https://github.com/Faire/mjml-react/blob/main/src/mjml/Mjml.tsx#L15)) so there should be no need for the `@types/mjml-react` package.

**Comment by kirill-konshin** [comment]
It helped, thanks! I'd suggest to fix mailing documentation to point to new lib.
