### ISSUE TITLE
`fontWeight` attribute assignable to `string` | `number`

### ISSUE THREAD

**Issue by jlarmstrongiv** [Faire/mjml-react#113]
I’m using some duplicate properties in inline styles (e.g. `React.CSSProperties`) and mjml props (e.g. `IMjmlTextProps`).

However, they are unable to share `fontWeight` as `React.CSSProperties` expects a string, while `IMjmlTextProps` expects a number.  It would be great to add `| number` in [all interfaces](https://github.com/search?q=repo%3AFaire%2Fmjml-react+weight&type=code) where `fontWeight` is defined.

Related
- Previously discussed in https://github.com/Faire/mjml-react/pull/81
- Also discussed in mjml https://github.com/mjmlio/mjml/issues/1769

**Comment by jlarmstrongiv** [comment]
A quick fix is to run 
```shell
# avoid mac and linux inconsistencies with perl https://stackoverflow.com/a/54932255
find . -name '*.ts' -exec perl -pi -e 's/fontWeight\?: string/fontWeight\?: string | number/g' {} \;
```

in your `node_modules/@faire/mjml-react` folder, followed by running

```shell
npx patch-package @faire/mjml-react
```

But, it would be much better to have a permanent solution

**Comment by emmclaughlin** [comment]
Hi @jlarmstrongiv 🙂 

@faire/mjml-react uses a script ([generate-mjml-react]) to generate these type files. In that script we import the mjml component from mjml and [determine its types based on the code definition](https://github.com/Faire/mjml-react/blob/main/scripts/generate-mjml-react.ts#L114-L124). As mentioned in https://github.com/Faire/mjml-react/pull/81, mjml defines `font-weight` as a string [here](https://github.com/mjmlio/mjml/blob/85bc58e9e2a88cef7424dc2fce3d889f66fb4298/packages/mjml-text/src/index.js#L18). We could add an override in the mjml-react script but the main goal of mjml-react is to have the type safety be aligned with what mjml is expecting.

It looks like in the mjml docs [mj-text](https://documentation.mjml.io/#mj-text) says it takes a number for font-weight, so one of them is possibly a mistake. I think the best permanent solution to this would be to adjust the mjml code to be 'string | number' if mjml truly accepts both for the font-weight.
