### ISSUE TITLE
`<MjmlRaw>` escapes HTML characters

### ISSUE THREAD

**Issue by nahtnam** [Faire/mjml-react#15]
Hello,

I'm trying to add some custom templating from an external backend library (like mustache) and I'm noticing that certain characters are being escaped.

For example:

```
<MjmlRaw>{`%{ forall x <- xs }`}</MjmlRaw>
```

gets converted to

```
%{ forall x &lt;- xs }
```

Dropping this in the MJML live editor doesn't have the same problem: https://mjml.io/try-it-live/JFNNq1k86 (Although it does trip up the syntax highlighting with the `<-`)

Reproduced example with mjml-react: https://codesandbox.io/s/magical-browser-zt96bj?file=/src/index.tsx

I tried to spend some time figuring out what portion of the library caused the escaping but couldn't really figure it out. Our temporary solution might be to just unescape the whole file (or anything within `{}`)

Any pointers would be appreciated, thanks!

**Comment by nahtnam** [comment]
Hey, super sorry for the late response, was on PTO!

Here is what we ended with:

```
import React, {PropsWithChildren} from 'react'

export function Raw(props: PropsWithChildren<unknown>) {
  const {children} = props
  return React.createElement('mj-raw', {
    dangerouslySetInnerHTML: {
      __html: children,
    },
  })
}

```

Seemingly works well and pretty simple

**Comment by emmclaughlin** [comment]
@nahtnam glad you have a working solution! We do have a PR up to expose `dangerouslySetInnerHTML` on all ending tags in the V3 release as well: https://github.com/Faire/mjml-react/pull/42#issue-1421350357. Feel free to leave us any feedback you have on the approach

**Comment by emmclaughlin** [comment]
Closing as there is currently a workaround and we have a plan to support this in V3 (see #42)
