### ISSUE TITLE
better expose render methods

### ISSUE THREAD

**Issue by rolznz** [Faire/mjml-react#64]
Unlike the example in the README, I have to import directly from the source:

```
import { render } from "@faire/mjml-react/dist/src/utils/render";
```

# from maintainers
Ideally the goal would be:
```
import { render } from "@faire/mjml-react/renders";
```
Two blockers:
- [x] #71
- [ ] #72

**Comment by emmclaughlin** [comment]
Thank you for pointing this out @rolznz! This change was made intentionally so that users who don't want to use this render import don't need to install its dependencies, but we hadn't updated to reflect this in the READEME. This PR should address it: https://github.com/Faire/mjml-react/pull/65

**Comment by rolznz** [comment]
@emmclaughlin I looked at the PR. Isn't there another way you can expose the import without having to import from the dist directory? this seems wrong to me.

**Comment by emmclaughlin** [comment]
We need to keep the render function out of the main index.ts file in order to fix dependency issues (e.g. https://github.com/Faire/mjml-react/issues/36). That said, agree it feels odd with the dist directory, will see if we can clean that up

**Comment by IanEdington** [comment]
If anyone has ideas of how to make this better for both `esm` and `cjs` we'd love to get help with this.
