### ISSUE TITLE
Automatically bump package.json version

### ISSUE THREAD

**Issue by hchiufaire** [Faire/mjml-react#67]
`@semantic-release` supports this with their plugin @semantic-release/git ([see plugins](https://semantic-release.gitbook.io/semantic-release/extending/plugins-list))

It would have to be added in this order in the `package.json` plugin list for it to make a post-release commit that updates the version: https://github.com/Faire/mjml-react/blob/2e70ee23a8841489bfe5e2e4c378e765378b77f0/package.json#L114

The plugin was removed after the post-release [commit](https://github.com/Faire/mjml-react/commit/2e70ee23a8841489bfe5e2e4c378e765378b77f0) failed, since we were having trouble letting a token/bot commit on the protected `main` branch, requiring PR reviews.

related?: https://github.com/semantic-release/git/issues/196#issuecomment-601310576

**Comment by IanEdington** [comment]
won't do
