### ISSUE TITLE
Tailwind Support Feasibility? 

### ISSUE THREAD

**Issue by SSardorf** [Faire/mjml-react#70]
Hey,
 
Does anyone have an idea of how big of a workload implementing Tailwind would be?
Curious as to whether Tailwindcss support would even be feasible.

**Comment by IanEdington** [comment]
There was a conversation in the mjml slack channel about this: https://mjml.slack.com/archives/C12HESC2G/p1668923334850109

Here's my answer in that conversation:

I don't know enough about tailwindCSS build pipeline, but we use styled-components and found the best way to integrate them with mjml is in a post processing step (after getting the html).

1. inline as much css as possible
2. also add a `<style>` tag to `<head>`

We use juice for css inlining.

This is the relevant part of our build pipeline
```
  const css = getStyledComponentsStaticCss(styledComponentsStyleSheet.instance);
  const styleTag: string = css
    ? `<style type="text/css">${css}</style type="text/css">`
    : "";

  // inline only the styles from styled-components (style attributes are the best practice for email)
  let html = juice.inlineContent(mjmlHtml, css);
  //  add style tag for all styled-components styles (fallback for any styles that can't be inlined)
  html = styleTag ? html.replace("</head>", `${styleTag}</head>`) : html;
```

**Comment by IanEdington** [comment]
Basically the core requirements are available to add something like tailwindcss or any other css tool, It's just a matter of writing a custom renderer. These are the [renderers we have in the repo currently](https://github.com/Faire/mjml-react/tree/v3.0.0/src/utils). It's an area that could definitely use improvement. Please let us know if you build anything that could be included here.

**Comment by IanEdington** [comment]
Closing as I believe tailwind is supported. If someone figures out how to configure it please submit a section to the readme.
