### ISSUE TITLE
publish package from the `dist` folder

### ISSUE THREAD

**Issue by IanEdington** [Faire/mjml-react#71]
currently the package is published from the source root directory (`/`). This results in import statements like the following:

```
import { render } from "@faire/mjml-react/dist/src/utils/render";
```

At build time if we moved everything into `/dist` that's required to publish the package we could publish from within the `dist` folder resulting in import statements like this:

```
import { render } from "@faire/mjml-react/src/utils/render";
```

split out from #64

**Comment by emmclaughlin** [comment]
Fixed in #77
