### ISSUE TITLE
MjmlInclude

### ISSUE THREAD

**Issue by paulocf92** [Faire/mjml-react#91]
Does this port support MjmlInclude? Would you guys have any example or would it be better to simply include a React component?

**Comment by IanEdington** [comment]
Yes, you can import `MjmlInclude` and it will be converted to an `mjml-include` tag in the mjml output. You use it the same way it's [used in mjml](https://documentation.mjml.io/#mj-include).

`MjmlInclude` is very handy when you're transitioning from `.mjml` files to mjml in react. However, if you're building a new email I would strongly suggest using react components. They are MUCH more flexible and there's no downside to using them over MjmlInclude unless you have some emails in `.mjml` and others in `.tsx`.

**Comment by paulocf92** [comment]
That's just what I thought as well, components are much more flexible.

Thank you so much!
